### ISSUE TITLE
application.yml.template 这个配置文件内容有错

### ISSUE THREAD

**Issue by hdwmp123** [Wechat-Group/weixin-java-miniapp-demo#1]
logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG

wechat:
  cp:
    appid: 111
    secret: 111
    token: 111
    aesKey: 111
    msgDataFormat: JSON

应该写成 

logging:
  level:
    org.springframework.web: DEBUG
    com.github.binarywang.demo.wechat: DEBUG

wechat:
  miniapp:
    appid: 111
    secret: 111
    token: 111
    aesKey: 111
    msgDataFormat: JSON

**Comment by binarywang** [comment]
已修复，感谢及时提出~
